# Generated by Django 3.1.1 on 2020-09-25 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_bloglistingpage_posts_per_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglistingpage',
            name='posts_per_page',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
