# Generated by Django 3.1.1 on 2020-09-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200925_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='featured',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
