# Generated by Django 3.1.13 on 2021-08-18 10:30

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210505_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='author',
            field=models.CharField(blank=True, help_text='If value is empty, it will be filled by the current User.', max_length=255, null=True, validators=[blog.models.check_username_exists]),
        ),
    ]
