# Generated by Django 3.1.1 on 2021-05-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckan_pages', '0013_auto_20210505_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckanforpage',
            name='keywords',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='commercialpage',
            name='keywords',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='communitypage',
            name='keywords',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='featuredetailpage',
            name='keywords',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='featurespage',
            name='keywords',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='showcasepage',
            name='keywords',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
