# Generated by Django 3.1.1 on 2020-09-28 06:05

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200928_0605'),
        ('streams', '0002_auto_20200928_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='poweredcardhomeorderable',
            name='powered_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.poweredcard'),
        ),
        migrations.AddField(
            model_name='ckanforhomeorderable',
            name='ckan_for_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.ckanforcard'),
        ),
        migrations.AddField(
            model_name='ckanforhomeorderable',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ckan_for_cards', to='home.homepage'),
        ),
    ]
