# Generated by Django 3.1.1 on 2020-09-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200930_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='powering_opendata_images',
        ),
    ]
