# Generated by Django 3.1.1 on 2021-05-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_search_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='keywords',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
