# Generated by Django 3.1.1 on 2020-09-30 15:08

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_poweringimage'),
        ('home', '0003_auto_20200928_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoweringImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='powering_images', to='home.homepage')),
                ('powering_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.poweringimage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
