# Generated by Django 3.1.1 on 2020-09-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_poweringimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poweringimages',
            old_name='powering_images',
            new_name='powering_image',
        ),
    ]
