# Generated by Django 3.1.1 on 2021-04-20 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0006_remove_homepage_powering_opendata_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='home_page_subtitle_image',
            field=models.ForeignKey(blank=True, help_text='The image that goes under the home page subtitle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
