# Generated by Django 3.1.1 on 2020-09-28 06:05

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ckan_pages', '0002_auto_20200928_0605'),
        ('wagtailimages', '0022_uploadedimage'),
        ('streams', '0002_auto_20200928_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinggroups',
            name='working_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.workinggroup'),
        ),
        migrations.AddField(
            model_name='stewards',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stewards', to='ckan_pages.communitypage'),
        ),
        migrations.AddField(
            model_name='stewards',
            name='steward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.steward'),
        ),
        migrations.AddField(
            model_name='softwareengineers',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.softwareengineer'),
        ),
        migrations.AddField(
            model_name='softwareengineers',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='developers', to='ckan_pages.communitypage'),
        ),
        migrations.AddField(
            model_name='showcasesection3',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_section_3', to='ckan_pages.showcasepage'),
        ),
        migrations.AddField(
            model_name='showcasesection3',
            name='showcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.poweredcard'),
        ),
        migrations.AddField(
            model_name='showcasesection2',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_section_2', to='ckan_pages.showcasepage'),
        ),
        migrations.AddField(
            model_name='showcasesection2',
            name='showcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.poweredcard'),
        ),
        migrations.AddField(
            model_name='showcasesection1',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_section_1', to='ckan_pages.showcasepage'),
        ),
        migrations.AddField(
            model_name='showcasesection1',
            name='showcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.poweredcard'),
        ),
        migrations.AddField(
            model_name='generalfeatures',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.generalfeature'),
        ),
        migrations.AddField(
            model_name='generalfeatures',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_features', to='ckan_pages.featurespage'),
        ),
        migrations.AddField(
            model_name='feedbacksection2',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.feedback'),
        ),
        migrations.AddField(
            model_name='feedbacksection2',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_section_2', to='ckan_pages.showcasepage'),
        ),
        migrations.AddField(
            model_name='feedbacksection1',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.feedback'),
        ),
        migrations.AddField(
            model_name='feedbacksection1',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_section_1', to='ckan_pages.showcasepage'),
        ),
        migrations.AddField(
            model_name='features',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.feature'),
        ),
        migrations.AddField(
            model_name='features',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='ckan_pages.featurespage'),
        ),
        migrations.AddField(
            model_name='extensions',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.extension'),
        ),
        migrations.AddField(
            model_name='extensions',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='ckan_pages.featurespage'),
        ),
        migrations.AddField(
            model_name='communitypage',
            name='contributors_image',
            field=models.ForeignKey(help_text="Contributors' photos", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='communitypage',
            name='open_knowledge_foundation_image',
            field=models.ForeignKey(help_text='Open Knowledge Foundation block image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='ckanforfeatures',
            name='ckan_for_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.ckanforcard'),
        ),
        migrations.AddField(
            model_name='ckanforfeatures',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ckan_for_cards', to='ckan_pages.featurespage'),
        ),
    ]
