# Generated by Django 3.1.1 on 2020-09-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckan_pages', '0005_auto_20200928_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckanforpage',
            name='page_for',
            field=models.CharField(help_text='CKAN for: government / enterprise', max_length=512),
        ),
    ]
