# Generated by Django 3.1.1 on 2020-09-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckan_pages', '0007_auto_20200928_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckanforpage',
            name='page_title',
            field=models.CharField(default='Page title', help_text='Page title', max_length=512),
        ),
    ]
