# Generated by Django 3.1.1 on 2020-09-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckan_pages', '0009_featuredetailpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredetailpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtitle text under the header', max_length=512),
        ),
    ]
