# Generated by Django 3.1 on 2021-03-25 10:21

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ckan_pages', '0011_commercialpage_commercialsupportitem'),
        ('streams', '0004_commercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialsupportitem',
            name='commercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.commercial'),
        ),
        migrations.AddField(
            model_name='commercialsupportitem',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial', to='ckan_pages.commercialpage'),
        ),
    ]
