# Generated by Django 3.1.1 on 2020-09-25 06:44

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200925_0638'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customrendition',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customrendition',
            name='image',
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('post_image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add an Image', label='Image', required=True)), ('caption', wagtail.blocks.CharBlock(help_text='Provide a caption for the image', label='Caption', required=True))]))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CustomImage',
        ),
        migrations.DeleteModel(
            name='CustomRendition',
        ),
    ]
