# Generated by Django 3.1.1 on 2020-09-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200925_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostpage',
            old_name='post_sub_title',
            new_name='post_subtitle',
        ),
    ]
