# Generated by Django 3.1.1 on 2020-09-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_bloglistingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingpage',
            name='posts_per_page',
            field=models.IntegerField(default=1),
        ),
    ]
