# Generated by Django 3.1.1 on 2020-09-28 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpostpage_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostpage',
            name='date',
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
