# Generated by Django 3.1.1 on 2021-05-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210505_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingpage',
            name='keywords',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='keywords',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
