# Generated by Django 3.1.1 on 2020-09-23 15:02

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CkanForCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('card', wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(max_length=64, required=True)), ('text', wagtail.blocks.TextBlock(max_length=512, required=True)), ('link', wagtail.blocks.PageChooserBlock(help_text='Choose an internal page to link to', requuired=True)), ('link_text', wagtail.blocks.CharBlock(max_length=128, required=True))])),
            ],
            options={
                'verbose_name': 'Ckan for .. Card',
                'verbose_name_plural': 'Ckan for .. Cards',
            },
        ),
    ]
