# Generated by Django 3.1.1 on 2020-09-28 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailimages', '0022_uploadedimage'),
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the Extension', max_length=64)),
                ('author', models.CharField(help_text='Subtitle', max_length=128)),
                ('description', models.CharField(help_text='Subtitle', max_length=512)),
                ('rating', models.CharField(help_text='Add repository rating in this format: "4.51 (240)"', max_length=32)),
                ('url', models.URLField(help_text='Add this Extension URL')),
            ],
            options={
                'verbose_name': 'Extension',
                'verbose_name_plural': 'Extensions',
            },
        ),
        migrations.AlterModelOptions(
            name='ckanforcard',
            options={'verbose_name': 'Ckan for ... Card', 'verbose_name_plural': 'Ckan for ... Cards'},
        ),
        migrations.RemoveField(
            model_name='ckanforcard',
            name='card',
        ),
        migrations.RemoveField(
            model_name='ckanforcard',
            name='name',
        ),
        migrations.AddField(
            model_name='ckanforcard',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='ckanforcard',
            name='internal_page',
            field=models.ForeignKey(blank=True, help_text='Select an internal Page to link to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='ckanforcard',
            name='link_text',
            field=models.CharField(default='Link text', help_text='Add some text for the link', max_length=64),
        ),
        migrations.AddField(
            model_name='ckanforcard',
            name='text',
            field=models.TextField(default='Card text', help_text='Add some text to the card', max_length=1024),
        ),
        migrations.AddField(
            model_name='ckanforcard',
            name='title',
            field=models.CharField(default='Card title', help_text='Title of the card', max_length=64),
        ),
        migrations.CreateModel(
            name='WorkingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this working group', max_length=64)),
                ('description', models.TextField(help_text='Describe this working group', max_length=1024)),
                ('member_1_description', models.TextField(help_text='Describe this member', max_length=1024)),
                ('member_1_url', models.URLField(help_text='Provide this member URL', max_length=256)),
                ('member_2_description', models.TextField(help_text='Describe this member', max_length=1024)),
                ('member_2_url', models.URLField(help_text='Provide this member URL', max_length=256)),
                ('member_3_description', models.TextField(help_text='Describe this member', max_length=1024)),
                ('member_3_url', models.URLField(help_text='Provide this member URL', max_length=256)),
                ('additional_text', models.TextField(help_text='Describe this working group', max_length=2056)),
                ('email', models.EmailField(blank=True, help_text='Provide e-mail to contact Working Group', max_length=254, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('member_1_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('member_2_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('member_3_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Working Group',
                'verbose_name_plural': 'Working Groups',
            },
        ),
        migrations.CreateModel(
            name='Steward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=256)),
                ('about', models.TextField(max_length=1028)),
                ('mail', models.CharField(blank=True, max_length=512, null=True)),
                ('twitter', models.CharField(blank=True, max_length=512, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=512, null=True)),
                ('skype', models.CharField(blank=True, max_length=512, null=True)),
                ('github', models.CharField(blank=True, max_length=512, null=True)),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Steward',
                'verbose_name_plural': 'Stewards',
            },
        ),
        migrations.CreateModel(
            name='SoftwareEngineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=256)),
                ('twitter', models.CharField(blank=True, max_length=512, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=512, null=True)),
                ('github', models.CharField(blank=True, max_length=512, null=True)),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Software Engineer',
                'verbose_name_plural': 'Software Engineers',
            },
        ),
        migrations.CreateModel(
            name='PoweredCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the card', max_length=64)),
                ('text', models.TextField(help_text='Add some text to the card', max_length=1024)),
                ('link', models.URLField(help_text='Add a URL to the source site')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Powered by CKAN Card',
                'verbose_name_plural': 'Powered by CKAN Cards',
            },
        ),
        migrations.CreateModel(
            name='GeneralFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the General Feature', max_length=64)),
                ('sub_title', models.CharField(help_text='Subtitle', max_length=512)),
                ('text', models.TextField(help_text='Add some text to the Feature', max_length=2056)),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('read_more_page', models.ForeignKey(blank=True, help_text='Select an internal Page to link to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'General Feature',
                'verbose_name_plural': 'General Features',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person', max_length=64)),
                ('role', models.CharField(help_text='Who is the the person?', max_length=64)),
                ('text', models.TextField(help_text='What was told', max_length='2056')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the Feature', max_length=64)),
                ('sub_title', models.CharField(help_text='Subtitle', max_length=512)),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('read_more_page', models.ForeignKey(blank=True, help_text='Select an internal Page to link to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
