# Generated by Django 3.1.1 on 2020-09-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('streams', '0002_auto_20200928_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoweringImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the block', max_length=64)),
                ('link', models.URLField(help_text='Add a URL to the block')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
    ]
