# Generated by Django 3.1 on 2021-04-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_commercial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steward',
            name='role',
        ),
        migrations.AddField(
            model_name='steward',
            name='represented_by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
