# Generated by Django 3.1 on 2021-04-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_auto_20210406_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steward',
            old_name='mail',
            new_name='link',
        ),
    ]
